# 输出url格式还有点问题，我觉得这跟文件存储有关系
# https://python.plainenglish.io/python-fastapi-serving-images-mp3-files-etc-from-your-backend-for-beginners-a7aa6eaec2f8
# 我先存文件系统，并且url，我自己存文件系统担心并发问题

# import os
from DeepDream.deep_dream import deep_dream_simple
# print(os.getcwd())
# os.chdir('/code/app')
# print(os.getcwd())

from fastapi import FastAPI, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi import FastAPI, File, UploadFile, Form, BackgroundTasks
from fastapi.responses import FileResponse
from StyleTransfer.fast_style_transfer_for_arbitrary_styles import style_transfer_simple
import nest_asyncio
# import uvicorn
# from fastapi.staticfiles import StaticFiles


nest_asyncio.apply()

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'],
    allow_credentials=True,
    allow_methods=['*'],
    allow_headers=['*'],
)
 
@app.get('/')
async def root():
    return {'hello': 'world'}

@app.post("/generate")
# @app.post("/generate",

#     # Set what the media type will be in the autogenerated OpenAPI specification.
#     # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
#     responses = {
#         200: {
#             "content": {"image/png": {}}
#         }
#     }

#     # Prevent FastAPI from adding "application/json" as an additional
#     # response media type in the autogenerated OpenAPI specification.
#     # https://github.com/tiangolo/fastapi/issues/3258
#     response_class=Response,
# )
async def generate(
        parameter: str = Form(None),
        pic1: str = Form(None),
        pic2: str = Form(None),
        strategyType: int = Form(None),
        textDes: str = Form(None),
    ):
    # resolution: int = Form(None),
    #     iterations: int = Form(None),
    #     prompts: str = Form("Underwater City"),
    #     quality: str = Form("draft"),
    #     aspect: str = Form("square"),
    #     scale: float = Form(2.5),
    #     style: str = Form('image'),
    #     make_video: bool = Form(False),

    # torch.cuda.empty_cache()
    if strategyType == 1:
        img = style_transfer_simple(content_image_url=pic1, style_image_url=pic2, parameters=parameter)
    elif strategyType == 2:
        img = deep_dream_simple(img_url=pic1, parameters=parameter)
    elif strategyType == 3:
        img = text_to_image_simple(text=textDes,init_img=pic1, parameters=parameter)
 
 
    # return FileResponse('StyleTransfer/output/output.png', media_type="image/png")

    # 如果上面的不行
    return Response(content=img, media_type="image/png")

# app.mount("/output", StaticFiles(directory="static"), name="static")

# uvicorn.run(app, port=8000)